version: "3.8"

services:
  go-app:
    container_name: web-analyzer
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: unless-stopped